name: Python Microservice CI

# 1. When should this robot run? 
on:
  push:
    branches: [ "main" ]

# 2. What should the robot do?
jobs:
  test-code:
    # 3. Spin up a temporary Ubuntu Linux server
    runs-on: ubuntu-latest

    steps:
    # Step A: Download your code onto the temporary server
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step B: Install Python on that server
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    # Step C: Install your tools (Flask and Pytest)
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install Flask pytest

    # Step D: Run the exact command you just ran on your Mac!
    - name: Run Automated Tests
      run: |
        pytest
# Step D: Run the exact command you just ran on your Mac!
    - name: Run Automated Tests
      run: |
        pytest

    # Step E: Build the Docker Image (Only runs if tests pass!)
    - name: Build Docker Image
      run: docker build -t pipeline-app:latest .
